### PR TITLE
Restructuring channel density info in cell HTML page to better display cell densities

### PR DESCRIPTION
**Pull request by pgleeson**

### CODE REVIEW

**Comment by tarelli** [comment]
@pgleeson is this ready to be reviewed/merged?

**Comment by pgleeson** [comment]
Yes, it would be great if you can have a look. More to do, but much better that what's there at the moment for channel densities, etc.

**Comment by pgleeson** [comment]
Add view on relative cond densities...

selection_172

**Comment by pgleeson** [comment]
@tarelli When you have a chance to look at this, could you also check the existing channel rate variable plotting? I'm not sure it's been looked at much since the update to the plot widget. Try with the Na in the HH example: http://comodl.org/projects/hodgkin-huxley-tutorial
 Basically, the first plot in the list doesn't show, the rest do, and both show incorrect behaviour when the Home button is pressed:

selection_173

**Comment by tarelli** [comment]
@pgleeson looking good! We should probably remove now the Cell Visual menu from the OSB bar at the top, what do you think?

**Comment by pgleeson** [comment]
Thanks @tarelli. Yes, the CellVisual can probably go at this stage.

If you do get a chance to see what the issue is with the channel plots it would be great. If this works for  the basic set of channel rate variables I'll add some basic plotting of custom expressions with the org.lemsml.model etc. libraries.

**Pull request merged**
